export const ADD_ALBUM_TO_FAVOURITE = 'ADD_ALBUM_TO_FAVOURITE';
export const DELETE_ALBUM_FROM_FAVOURITE = 'DELETE_ALBUM_FROM_FAVOURITE';
export const RESET_FAVOURITE_ALBUM_LIST = 'RESET_FAVOURITE_ALBUM_LIST';

export const SET_SINGLE_ARTIST_NAME = 'SET_SINGLE_ARTIST_NAME';
export const RESET_SINGLE_ARTIST_NAME = 'RESET_SINGLE_ARTIST_NAME';