export const ADD_ARTIST_TO_FAVOURITE = 'ADD_ARTIST_TO_FAVOURITE';
export const DELETE_ARTIST_FROM_FAVOURITE = 'DELETE_ARTIST_FROM_FAVOURITE';
export const RESET_FAVOURITE_LIST = 'RESET_FAVOURITE_LIST';