export const GETTING_ALBUMS_OF_ARTIST = 'GETTING_ALBUMS_OF_ARTIST';
export const GETTING_ALBUMS_OF_ARTIST_SUCCESS = 'GETTING_ALBUMS_OF_ARTIST_SUCCESS';
export const GETTING_ALBUMS_OF_ARTIST_FAILURE = 'GETTING_ALBUMS_OF_ARTIST_FAILURE';
